export const seedOrganizations = [
  // Core Government
  { name: 'Prime Minister\'s Office', nameBn: 'প্রধানমন্ত্রীর কার্যালয়', slug: 'pmo', type: 'ministry' as const },

  // Ministries (A–Z)
  { name: 'Ministry of Agriculture', nameBn: 'কৃষি মন্ত্রণালয়', slug: 'ministry-agriculture', type: 'ministry' as const },
  { name: 'Ministry of Chittagong Hill Tracts Affairs', nameBn: 'পার্বত্য চট্টগ্রাম বিষয়ক মন্ত্রণালয়', slug: 'ministry-chta', type: 'ministry' as const },
  { name: 'Ministry of Civil Aviation and Tourism', nameBn: 'বেসামরিক বিমান পরিবহন ও পর্যটন মন্ত্রণালয়', slug: 'ministry-civil-aviation', type: 'ministry' as const },
  { name: 'Ministry of Commerce', nameBn: 'বাণিজ্য মন্ত্রণালয়', slug: 'ministry-commerce', type: 'ministry' as const },
  { name: 'Ministry of Communication', nameBn: 'যোগাযোগ মন্ত্রণালয়', slug: 'ministry-communication', type: 'ministry' as const },
  { name: 'Ministry of Cultural Affairs', nameBn: 'সংস্কৃতি বিষয়ক মন্ত্রণালয়', slug: 'ministry-culture', type: 'ministry' as const },
  { name: 'Ministry of Defence', nameBn: 'প্রতিরক্ষা মন্ত্রণালয়', slug: 'ministry-defence', type: 'ministry' as const },
  { name: 'Ministry of Disaster Management and Relief', nameBn: 'দুর্যোগ ব্যবস্থাপনা ও ত্রাণ মন্ত্রণালয়', slug: 'ministry-disaster', type: 'ministry' as const },
  { name: 'Ministry of Education', nameBn: 'শিক্ষা মন্ত্রণালয়', slug: 'ministry-education', type: 'ministry' as const },
  { name: "Ministry of Expatriates' Welfare and Overseas Employment", nameBn: 'প্রবাসী কল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়', slug: 'ministry-expatriates', type: 'ministry' as const },
  { name: 'Ministry of Finance', nameBn: 'অর্থ মন্ত্রণালয়', slug: 'ministry-finance', type: 'ministry' as const },
  { name: 'Ministry of Fisheries and Livestock', nameBn: 'মৎস্য ও প্রাণিসম্পদ মন্ত্রণালয়', slug: 'ministry-fisheries', type: 'ministry' as const },
  { name: 'Ministry of Food', nameBn: 'খাদ্য মন্ত্রণালয়', slug: 'ministry-food', type: 'ministry' as const },
  { name: 'Ministry of Foreign Affairs', nameBn: 'পররাষ্ট্র মন্ত্রণালয়', slug: 'ministry-foreign', type: 'ministry' as const },
  { name: 'Ministry of Health and Family Welfare', nameBn: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়', slug: 'ministry-health', type: 'ministry' as const },
  { name: 'Ministry of Home Affairs', nameBn: 'স্বরাষ্ট্র মন্ত্রণালয়', slug: 'ministry-home', type: 'ministry' as const },
  { name: 'Ministry of Housing and Public Works', nameBn: 'গৃহায়ন ও গণপূর্ত মন্ত্রণালয়', slug: 'ministry-housing', type: 'ministry' as const },
  { name: 'Ministry of Industries', nameBn: 'শিল্প মন্ত্রণালয়', slug: 'ministry-industries', type: 'ministry' as const },
  { name: 'Ministry of Information and Broadcasting', nameBn: 'তথ্য ও সম্প্রচার মন্ত্রণালয়', slug: 'ministry-information', type: 'ministry' as const },
  { name: 'Ministry of Labour and Employment', nameBn: 'শ্রম ও কর্মসংস্থান মন্ত্রণালয়', slug: 'ministry-labour', type: 'ministry' as const },
  { name: 'Ministry of Land', nameBn: 'ভূমি মন্ত্রণালয়', slug: 'ministry-land', type: 'ministry' as const },
  { name: 'Ministry of Law, Justice and Parliamentary Affairs', nameBn: 'আইন, বিচার ও সংসদ বিষয়ক মন্ত্রণালয়', slug: 'ministry-law', type: 'ministry' as const },
  { name: 'Ministry of Liberation War Affairs', nameBn: 'মুক্তিযুদ্ধ বিষয়ক মন্ত্রণালয়', slug: 'ministry-liberation-war', type: 'ministry' as const },
  { name: 'Ministry of Local Government, Rural Development and Cooperatives', nameBn: 'স্থানীয় সরকার, পল্লী উন্নয়ন ও সমবায় মন্ত্রণালয়', slug: 'ministry-lgrd', type: 'ministry' as const },
  { name: 'Ministry of Planning', nameBn: 'পরিকল্পনা মন্ত্রণালয়', slug: 'ministry-planning', type: 'ministry' as const },
  { name: 'Ministry of Posts, Telecommunications and Information Technology', nameBn: 'ডাক, টেলিযোগাযোগ ও তথ্যপ্রযুক্তি মন্ত্রণালয়', slug: 'ministry-posts-ict', type: 'ministry' as const },
  { name: 'Ministry of Power, Energy and Mineral Resources', nameBn: 'বিদ্যুৎ, জ্বালানি ও খনিজ সম্পদ মন্ত্রণালয়', slug: 'ministry-power-energy', type: 'ministry' as const },
  { name: 'Ministry of Primary and Mass Education', nameBn: 'প্রাথমিক ও গণশিক্ষা মন্ত্রণালয়', slug: 'ministry-primary-education', type: 'ministry' as const },
  { name: 'Ministry of Public Administration', nameBn: 'জনপ্রশাসন মন্ত্রণালয়', slug: 'ministry-public-admin', type: 'ministry' as const },
  { name: 'Ministry of Religious Affairs', nameBn: 'ধর্ম বিষয়ক মন্ত্রণালয়', slug: 'ministry-religious', type: 'ministry' as const },
  { name: 'Ministry of Science and Technology', nameBn: 'বিজ্ঞান ও প্রযুক্তি মন্ত্রণালয়', slug: 'ministry-science', type: 'ministry' as const },
  { name: 'Ministry of Shipping', nameBn: 'নৌপরিবহন মন্ত্রণালয়', slug: 'ministry-shipping', type: 'ministry' as const },
  { name: 'Ministry of Social Welfare', nameBn: 'সমাজকল্যাণ মন্ত্রণালয়', slug: 'ministry-social-welfare', type: 'ministry' as const },
  { name: 'Ministry of Textiles and Jute', nameBn: 'বস্ত্র ও পাট মন্ত্রণালয়', slug: 'ministry-textiles', type: 'ministry' as const },
  { name: 'Ministry of Water Resources', nameBn: 'পানি সম্পদ মন্ত্রণালয়', slug: 'ministry-water', type: 'ministry' as const },
  { name: 'Ministry of Women and Children Affairs', nameBn: 'মহিলা ও শিশু বিষয়ক মন্ত্রণালয়', slug: 'ministry-women', type: 'ministry' as const },
  { name: 'Ministry of Youth and Sports', nameBn: 'যুব ও ক্রীড়া মন্ত্রণালয়', slug: 'ministry-youth-sports', type: 'ministry' as const },

  // Regulatory Bodies and Authorities
  { name: 'Bangladesh Telecommunication Regulatory Commission', slug: 'btrc', type: 'authority' as const },
  { name: 'National Board of Revenue', nameBn: 'জাতীয় রাজস্ব বোর্ড', slug: 'nbr', type: 'authority' as const },
  { name: 'Bangladesh Bank', nameBn: 'বাংলাদেশ ব্যাংক', slug: 'bangladesh-bank', type: 'authority' as const },
  { name: 'Bangladesh Election Commission', slug: 'election-commission', type: 'authority' as const },
  { name: 'Bangladesh Road Transport Authority', slug: 'brta', type: 'authority' as const },
  { name: 'Bangladesh Civil Aviation Authority', slug: 'bangladesh-civil-aviation', type: 'authority' as const },
  { name: 'Bangladesh Securities and Exchange Commission', nameBn: 'বাংলাদেশ সিকিউরিটিজ অ্যান্ড এক্সচেঞ্জ কমিশন', slug: 'bsec', type: 'authority' as const },
  { name: 'Bangladesh Standards and Testing Institution', slug: 'bsti', type: 'authority' as const },
  { name: 'Bangladesh Energy Regulatory Commission', slug: 'berc', type: 'authority' as const },
  { name: 'Bangladesh Power Development Board', nameBn: 'বাংলাদেশ বিদ্যুৎ উন্নয়ন বোর্ড', slug: 'bpdb', type: 'authority' as const },
  { name: 'Bangladesh Rural Electrification Board', nameBn: 'বাংলাদেশ পল্লী বিদ্যুতায়ন বোর্ড', slug: 'reb', type: 'authority' as const },
  { name: 'Bangladesh Public Service Commission', nameBn: 'বাংলাদেশ সরকারি কর্ম কমিশন', slug: 'bpsc', type: 'authority' as const },
  { name: 'Bangladesh Investment Development Authority', slug: 'bida', type: 'authority' as const },
  { name: 'Bangladesh Export Processing Zones Authority', slug: 'bepza', type: 'authority' as const },
  { name: 'Bangladesh Economic Zones Authority', slug: 'beza', type: 'authority' as const },
  { name: 'Anti-Corruption Commission', nameBn: 'দুর্নীতি দমন কমিশন', slug: 'acc', type: 'authority' as const },

  // Departments
  { name: 'Bangladesh Police', nameBn: 'বাংলাদেশ পুলিশ', slug: 'bangladesh-police', type: 'department' as const },
  { name: 'Directorate General of Immigration & Passports', slug: 'dgip', type: 'department' as const },
  { name: 'Registrar General, Birth & Death Registration', slug: 'bdris', type: 'department' as const },
  { name: 'National Identity Registration Wing', slug: 'nid-wing', type: 'department' as const },
  { name: 'Directorate General of Health Services', nameBn: 'স্বাস্থ্য অধিদপ্তর', slug: 'dghs', type: 'department' as const },
  { name: 'Directorate of Primary Education', nameBn: 'প্রাথমিক শিক্ষা অধিদপ্তর', slug: 'dpe', type: 'department' as const },
  { name: 'Department of Environment', nameBn: 'পরিবেশ অধিদপ্তর', slug: 'doe', type: 'department' as const },
  { name: 'Bangladesh Forest Department', slug: 'bforest', type: 'department' as const },
  { name: 'Department of Fisheries', nameBn: 'মৎস্য অধিদপ্তর', slug: 'dof', type: 'department' as const },
  { name: 'Bangladesh Meteorological Department', nameBn: 'আবহাওয়া অধিদপ্তর', slug: 'bmd', type: 'department' as const },
  { name: 'Department of Public Health Engineering', slug: 'dphe', type: 'department' as const },
  { name: 'Directorate General of Food', nameBn: 'খাদ্য অধিদপ্তর', slug: 'dgfood', type: 'department' as const },
];

export const seedWebsites = [
  // ── National Portal & PMO ────────────────────────────────────────────────
  { url: 'https://bangladesh.gov.bd', domain: 'bangladesh.gov.bd', tld: 'gov.bd', orgSlug: 'pmo', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://pmo.gov.bd', domain: 'pmo.gov.bd', tld: 'gov.bd', orgSlug: 'pmo', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://cabinet.gov.bd', domain: 'cabinet.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.parliament.gov.bd', domain: 'parliament.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://supremecourt.gov.bd', domain: 'supremecourt.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },

  // ── Ministries ────────────────────────────────────────────────────────────
  { url: 'https://moa.gov.bd', domain: 'moa.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-agriculture', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mochta.gov.bd', domain: 'mochta.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-chta', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mocat.gov.bd', domain: 'mocat.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-civil-aviation', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mincom.gov.bd', domain: 'mincom.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-communication', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moca.gov.bd', domain: 'moca.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-culture', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mod.gov.bd', domain: 'mod.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-defence', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://modmr.gov.bd', domain: 'modmr.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-disaster', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moedu.gov.bd', domain: 'moedu.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-education', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://probashi.gov.bd', domain: 'probashi.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-expatriates', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mof.gov.bd', domain: 'mof.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-finance', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mofl.gov.bd', domain: 'mofl.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-fisheries', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mofood.gov.bd', domain: 'mofood.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-food', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mofa.gov.bd', domain: 'mofa.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-foreign', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mohfw.gov.bd', domain: 'mohfw.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-health', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mha.gov.bd', domain: 'mha.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-home', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mohpw.gov.bd', domain: 'mohpw.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-housing', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moind.gov.bd', domain: 'moind.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-industries', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moi.gov.bd', domain: 'moi.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-information', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mole.gov.bd', domain: 'mole.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-labour', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://minland.gov.bd', domain: 'minland.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-land', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://molaw.gov.bd', domain: 'molaw.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-law', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://molwa.gov.bd', domain: 'molwa.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-liberation-war', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://lgd.gov.bd', domain: 'lgd.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-lgrd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mopa.gov.bd', domain: 'mopa.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-public-admin', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://planning.gov.bd', domain: 'planning.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-planning', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moshict.gov.bd', domain: 'moshict.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-posts-ict', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://powerdivision.gov.bd', domain: 'powerdivision.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-power-energy', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mopme.gov.bd', domain: 'mopme.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-primary-education', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mora.gov.bd', domain: 'mora.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-religious', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://most.gov.bd', domain: 'most.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-science', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mos.gov.bd', domain: 'mos.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-shipping', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://msw.gov.bd', domain: 'msw.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-social-welfare', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://motj.gov.bd', domain: 'motj.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-textiles', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mowr.gov.bd', domain: 'mowr.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-water', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mowca.gov.bd', domain: 'mowca.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-women', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moys.gov.bd', domain: 'moys.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-youth-sports', discoverySource: 'seed', verifiedGov: true },

  // ── Regulatory & Statutory Bodies ─────────────────────────────────────────
  { url: 'https://btrc.gov.bd', domain: 'btrc.gov.bd', tld: 'gov.bd', orgSlug: 'btrc', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://nbr.gov.bd', domain: 'nbr.gov.bd', tld: 'gov.bd', orgSlug: 'nbr', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.bb.org.bd', domain: 'bb.org.bd', tld: 'org.bd', orgSlug: 'bangladesh-bank', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://ecs.gov.bd', domain: 'ecs.gov.bd', tld: 'gov.bd', orgSlug: 'election-commission', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.brta.gov.bd', domain: 'brta.gov.bd', tld: 'gov.bd', orgSlug: 'brta', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.caab.gov.bd', domain: 'caab.gov.bd', tld: 'gov.bd', orgSlug: 'bangladesh-civil-aviation', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://sec.gov.bd', domain: 'sec.gov.bd', tld: 'gov.bd', orgSlug: 'bsec', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bsti.gov.bd', domain: 'bsti.gov.bd', tld: 'gov.bd', orgSlug: 'bsti', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://berc.gov.bd', domain: 'berc.gov.bd', tld: 'gov.bd', orgSlug: 'berc', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bpdb.gov.bd', domain: 'bpdb.gov.bd', tld: 'gov.bd', orgSlug: 'bpdb', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://reb.gov.bd', domain: 'reb.gov.bd', tld: 'gov.bd', orgSlug: 'reb', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bpsc.gov.bd', domain: 'bpsc.gov.bd', tld: 'gov.bd', orgSlug: 'bpsc', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bida.gov.bd', domain: 'bida.gov.bd', tld: 'gov.bd', orgSlug: 'bida', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.bepza.gov.bd', domain: 'bepza.gov.bd', tld: 'gov.bd', orgSlug: 'bepza', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://beza.gov.bd', domain: 'beza.gov.bd', tld: 'gov.bd', orgSlug: 'beza', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://acc.gov.bd', domain: 'acc.gov.bd', tld: 'gov.bd', orgSlug: 'acc', discoverySource: 'seed', verifiedGov: true },

  // ── Departments ───────────────────────────────────────────────────────────
  { url: 'https://www.police.gov.bd', domain: 'police.gov.bd', tld: 'gov.bd', orgSlug: 'bangladesh-police', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.dip.gov.bd', domain: 'dip.gov.bd', tld: 'gov.bd', orgSlug: 'dgip', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bdris.gov.bd', domain: 'bdris.gov.bd', tld: 'gov.bd', orgSlug: 'bdris', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://services.nidw.gov.bd', domain: 'services.nidw.gov.bd', tld: 'gov.bd', orgSlug: 'nid-wing', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dghs.gov.bd', domain: 'dghs.gov.bd', tld: 'gov.bd', orgSlug: 'dghs', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dpe.gov.bd', domain: 'dpe.gov.bd', tld: 'gov.bd', orgSlug: 'dpe', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://doe.gov.bd', domain: 'doe.gov.bd', tld: 'gov.bd', orgSlug: 'doe', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bforest.gov.bd', domain: 'bforest.gov.bd', tld: 'gov.bd', orgSlug: 'bforest', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://fisheries.gov.bd', domain: 'fisheries.gov.bd', tld: 'gov.bd', orgSlug: 'dof', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bmd.gov.bd', domain: 'bmd.gov.bd', tld: 'gov.bd', orgSlug: 'bmd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dphe.gov.bd', domain: 'dphe.gov.bd', tld: 'gov.bd', orgSlug: 'dphe', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dgfood.gov.bd', domain: 'dgfood.gov.bd', tld: 'gov.bd', orgSlug: 'dgfood', discoverySource: 'seed', verifiedGov: true },

  // ── Other Key Agencies & Corporations ────────────────────────────────────
  { url: 'https://www.bbs.gov.bd', domain: 'bbs.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.cga.gov.bd', domain: 'cga.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.imed.gov.bd', domain: 'imed.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.epb.gov.bd', domain: 'epb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dgda.gov.bd', domain: 'dgda.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dae.gov.bd', domain: 'dae.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://nctb.gov.bd', domain: 'nctb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://ugc.gov.bd', domain: 'ugc.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bmet.gov.bd', domain: 'bmet.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dgm.gov.bd', domain: 'dgm.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.doi.gov.bd', domain: 'doi.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://rjsc.gov.bd', domain: 'rjsc.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dpdt.gov.bd', domain: 'dpdt.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://erd.gov.bd', domain: 'erd.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://baec.gov.bd', domain: 'baec.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://sparrso.gov.bd', domain: 'sparrso.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bcc.gov.bd', domain: 'bcc.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://a2i.gov.bd', domain: 'a2i.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://petrobangla.org.bd', domain: 'petrobangla.org.bd', tld: 'org.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bpc.gov.bd', domain: 'bpc.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://parjatan.gov.bd', domain: 'parjatan.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bscic.gov.bd', domain: 'bscic.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bsfic.gov.bd', domain: 'bsfic.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://btcl.gov.bd', domain: 'btcl.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bhb.gov.bd', domain: 'bhb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bwdb.gov.bd', domain: 'bwdb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.mowdb.gov.bd', domain: 'mowdb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moenr.gov.bd', domain: 'moenr.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://minenv.gov.bd', domain: 'minenv.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moef.gov.bd', domain: 'moef.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mopt.gov.bd', domain: 'mopt.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mot.gov.bd', domain: 'mot.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mrt.gov.bd', domain: 'mrt.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.cirdap.org', domain: 'cirdap.org', tld: 'org', discoverySource: 'seed', verifiedGov: false },

  // ── Divisions (8 Administrative Divisions) ────────────────────────────────
  { url: 'https://dhaka.gov.bd', domain: 'dhaka.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://chattogram.gov.bd', domain: 'chattogram.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://sylhet.gov.bd', domain: 'sylhet.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://rajshahi.gov.bd', domain: 'rajshahi.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://khulna.gov.bd', domain: 'khulna.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://barishal.gov.bd', domain: 'barishal.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://rangpur.gov.bd', domain: 'rangpur.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mymensingh.gov.bd', domain: 'mymensingh.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },

  // ── Public Universities ───────────────────────────────────────────────────
  { url: 'https://du.ac.bd', domain: 'du.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://buet.ac.bd', domain: 'buet.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://ru.ac.bd', domain: 'ru.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://cu.ac.bd', domain: 'cu.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://ku.ac.bd', domain: 'ku.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bau.edu.bd', domain: 'bau.edu.bd', tld: 'edu.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://nu.ac.bd', domain: 'nu.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bou.edu.bd', domain: 'bou.edu.bd', tld: 'edu.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://juniv.edu', domain: 'juniv.edu', tld: 'edu', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://sust.edu', domain: 'sust.edu', tld: 'edu', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://duet.ac.bd', domain: 'duet.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://cuet.ac.bd', domain: 'cuet.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://ruet.ac.bd', domain: 'ruet.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://kuet.ac.bd', domain: 'kuet.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bsmmu.edu.bd', domain: 'bsmmu.edu.bd', tld: 'edu.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bsmrau.edu.bd', domain: 'bsmrau.edu.bd', tld: 'edu.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://sau.edu.bd', domain: 'sau.edu.bd', tld: 'edu.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://iu.ac.bd', domain: 'iu.ac.bd', tld: 'ac.bd', discoverySource: 'seed', verifiedGov: true },
];
