export const seedOrganizations = [
  { name: 'Prime Minister\'s Office', nameBn: 'প্রধানমন্ত্রীর কার্যালয়', slug: 'pmo', type: 'ministry' as const },
  { name: 'Ministry of Finance', nameBn: 'অর্থ মন্ত্রণালয়', slug: 'ministry-finance', type: 'ministry' as const },
  { name: 'Ministry of Health and Family Welfare', nameBn: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়', slug: 'ministry-health', type: 'ministry' as const },
  { name: 'Ministry of Education', nameBn: 'শিক্ষা মন্ত্রণালয়', slug: 'ministry-education', type: 'ministry' as const },
  { name: 'Ministry of Home Affairs', nameBn: 'স্বরাষ্ট্র মন্ত্রণালয়', slug: 'ministry-home', type: 'ministry' as const },
  { name: 'Ministry of Foreign Affairs', nameBn: 'পররাষ্ট্র মন্ত্রণালয়', slug: 'ministry-foreign', type: 'ministry' as const },
  { name: 'Ministry of Agriculture', nameBn: 'কৃষি মন্ত্রণালয়', slug: 'ministry-agriculture', type: 'ministry' as const },
  { name: 'Ministry of Commerce', nameBn: 'বাণিজ্য মন্ত্রণালয়', slug: 'ministry-commerce', type: 'ministry' as const },
  { name: 'Ministry of Communication', nameBn: 'যোগাযোগ মন্ত্রণালয়', slug: 'ministry-communication', type: 'ministry' as const },
  { name: 'Ministry of Law, Justice and Parliamentary Affairs', nameBn: 'আইন, বিচার ও সংসদ বিষয়ক মন্ত্রণালয়', slug: 'ministry-law', type: 'ministry' as const },
  { name: 'Bangladesh Telecommunication Regulatory Commission', slug: 'btrc', type: 'authority' as const },
  { name: 'National Board of Revenue', nameBn: 'জাতীয় রাজস্ব বোর্ড', slug: 'nbr', type: 'authority' as const },
  { name: 'Bangladesh Bank', nameBn: 'বাংলাদেশ ব্যাংক', slug: 'bangladesh-bank', type: 'authority' as const },
  { name: 'Bangladesh Election Commission', slug: 'election-commission', type: 'authority' as const },
  { name: 'Bangladesh Police', nameBn: 'বাংলাদেশ পুলিশ', slug: 'bangladesh-police', type: 'department' as const },
  { name: 'Directorate General of Immigration & Passports', slug: 'dgip', type: 'department' as const },
  { name: 'Bangladesh Road Transport Authority', slug: 'brta', type: 'authority' as const },
  { name: 'Registrar General, Birth & Death Registration', slug: 'bdris', type: 'department' as const },
  { name: 'National Identity Registration Wing', slug: 'nid-wing', type: 'department' as const },
  { name: 'Bangladesh Civil Aviation Authority', slug: 'caab', type: 'authority' as const },
];

export const seedWebsites = [
  // National Portal & PMO
  { url: 'https://bangladesh.gov.bd', domain: 'bangladesh.gov.bd', tld: 'gov.bd', orgSlug: 'pmo', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://pmo.gov.bd', domain: 'pmo.gov.bd', tld: 'gov.bd', orgSlug: 'pmo', discoverySource: 'seed', verifiedGov: true },

  // Core Ministries
  { url: 'https://mof.gov.bd', domain: 'mof.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-finance', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mohfw.gov.bd', domain: 'mohfw.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-health', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moedu.gov.bd', domain: 'moedu.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-education', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mha.gov.bd', domain: 'mha.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-home', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mofa.gov.bd', domain: 'mofa.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-foreign', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moa.gov.bd', domain: 'moa.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-agriculture', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mincom.gov.bd', domain: 'mincom.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-communication', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://molaw.gov.bd', domain: 'molaw.gov.bd', tld: 'gov.bd', orgSlug: 'ministry-law', discoverySource: 'seed', verifiedGov: true },

  // Key Authorities & Agencies
  { url: 'https://btrc.gov.bd', domain: 'btrc.gov.bd', tld: 'gov.bd', orgSlug: 'btrc', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://nbr.gov.bd', domain: 'nbr.gov.bd', tld: 'gov.bd', orgSlug: 'nbr', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.bb.org.bd', domain: 'bb.org.bd', tld: 'org.bd', orgSlug: 'bangladesh-bank', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://ecs.gov.bd', domain: 'ecs.gov.bd', tld: 'gov.bd', orgSlug: 'election-commission', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.police.gov.bd', domain: 'police.gov.bd', tld: 'gov.bd', orgSlug: 'bangladesh-police', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.dip.gov.bd', domain: 'dip.gov.bd', tld: 'gov.bd', orgSlug: 'dgip', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.brta.gov.bd', domain: 'brta.gov.bd', tld: 'gov.bd', orgSlug: 'brta', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bdris.gov.bd', domain: 'bdris.gov.bd', tld: 'gov.bd', orgSlug: 'bdris', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://services.nidw.gov.bd', domain: 'services.nidw.gov.bd', tld: 'gov.bd', orgSlug: 'nid-wing', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.caab.gov.bd', domain: 'caab.gov.bd', tld: 'gov.bd', orgSlug: 'bangladesh-civil-aviation', discoverySource: 'seed', verifiedGov: true },

  // Additional well-known gov sites
  { url: 'https://www.bbs.gov.bd', domain: 'bbs.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dgda.gov.bd', domain: 'dgda.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dae.gov.bd', domain: 'dae.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.bepza.gov.bd', domain: 'bepza.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://beza.gov.bd', domain: 'beza.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://acc.gov.bd', domain: 'acc.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.cga.gov.bd', domain: 'cga.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.imed.gov.bd', domain: 'imed.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.epb.gov.bd', domain: 'epb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bida.gov.bd', domain: 'bida.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.doi.gov.bd', domain: 'doi.gov.bd', tlt: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://bmet.gov.bd', domain: 'bmet.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://dgm.gov.bd', domain: 'dgm.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.cirdap.org', domain: 'cirdap.org', tld: 'org', discoverySource: 'seed', verifiedGov: false },
  { url: 'https://mopa.gov.bd', domain: 'mopa.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://minland.gov.bd', domain: 'minland.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.mowca.gov.bd', domain: 'mowca.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://msw.gov.bd', domain: 'msw.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://minenv.gov.bd', domain: 'minenv.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moef.gov.bd', domain: 'moef.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mopt.gov.bd', domain: 'mopt.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://moshict.gov.bd', domain: 'moshict.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mot.gov.bd', domain: 'mot.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mrt.gov.bd', domain: 'mrt.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://mowdb.gov.bd', domain: 'mowdb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://nctb.gov.bd', domain: 'nctb.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://ugc.gov.bd', domain: 'ugc.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://www.parliament.gov.bd', domain: 'parliament.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://supremecourt.gov.bd', domain: 'supremecourt.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
  { url: 'https://cabinet.gov.bd', domain: 'cabinet.gov.bd', tld: 'gov.bd', discoverySource: 'seed', verifiedGov: true },
];
